name: Deploy

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            allow-import-from-derivation = false
            extra-substituters = https://isabelroses.cachix.org
            extra-trusted-public-keys = isabelroses.cachix.org-1:mXdV/CMcPDaiTmkQ7/4+MzChpOe6Cb97njKmBQQmLPM=

      - name: Build
        run: nix run github:isabelroses/ringfairy

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: dist

      - name: Publish deployed code
        uses: actions/upload-artifact@v4
        with:
          name: published
          path: dist
